# Generated by Django 4.0.5 on 2022-07-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std_model',
            fields=[
                ('std_number', models.IntegerField(primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
