# Generated by Django 4.0.5 on 2022-07-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std_model',
            old_name='std_number',
            new_name='personal_No',
        ),
    ]
