# Generated by Django 4.0.5 on 2022-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0002_rename_std_number_std_model_personal_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_model',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
