# Generated by Django 4.0.5 on 2022-07-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0003_std_model_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_model',
            name='repeat_personal_No',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
