# Generated by Django 4.0.5 on 2022-07-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibralianModel',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
