# Generated by Django 4.0.5 on 2022-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libralianmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
