# Generated by Django 4.0.5 on 2022-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0002_libralianmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='libralianmodel',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
