# Generated by Django 4.0.5 on 2022-07-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0004_alter_libralianmodel_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='libralianmodel',
            name='libralian_no',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
