# Generated by Django 4.0.6 on 2022-07-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('std_app', '0005_rename_repeat_personal_no_std_model_std_personal_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=70)),
                ('publication_date', models.DateField(verbose_name='publication date')),
                ('subject_area', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=40)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowedbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('bks_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homeapp.books')),
                ('std_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='std_app.std_model')),
            ],
        ),
    ]
