# Generated by Django 4.0.5 on 2022-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='availablile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
