# Generated by Django 4.0.5 on 2022-07-07 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0002_books_availablile_alter_books_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowedbooks',
            fields=[
                ('bks_id', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bk_id', serialize=False, to='Homeapp.books')),
                ('borrow_date', models.DateField(default=datetime.date(2022, 7, 8), editable=False)),
            ],
        ),
        migrations.RenameField(
            model_name='books',
            old_name='availablile',
            new_name='availability',
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(verbose_name='publication date'),
        ),
    ]
