# Generated by Django 4.0.5 on 2022-07-07 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0002_rename_std_number_std_model_personal_no'),
        ('Homeapp', '0003_borrowedbooks_rename_availablile_books_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbooks',
            name='std_number',
            field=models.OneToOneField(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='stdNumber', to='std_app.std_model'),
            preserve_default=False,
        ),
    ]
