# Generated by Django 4.0.5 on 2022-07-08 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0004_borrowedbooks_std_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
