# Generated by Django 4.0.5 on 2022-07-08 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0005_alter_borrowedbooks_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='borrow_date',
            field=models.DateField(default=datetime.date(2022, 7, 8), editable=False),
        ),
    ]
