# Generated by Django 4.0.5 on 2022-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0006_alter_borrowedbooks_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
