# Generated by Django 4.0.5 on 2022-07-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0007_alter_borrowedbooks_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
