# Generated by Django 4.0.5 on 2022-07-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0013_alter_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbooks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowedbooks',
            name='bks_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookid', to='Homeapp.books'),
        ),
    ]
