# Generated by Django 4.0.6 on 2022-07-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0005_rename_repeat_personal_no_std_model_std_personal_no'),
        ('Homeapp', '0015_alter_books_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='bks_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homeapp.books'),
        ),
        migrations.AlterField(
            model_name='borrowedbooks',
            name='std_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='std_app.std_model'),
        ),
    ]
