# Generated by Django 4.0.6 on 2022-07-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0016_alter_borrowedbooks_bks_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='id',
            new_name='itd',
        ),
    ]
