# Generated by Django 4.0.6 on 2022-07-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0017_rename_id_books_itd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='itd',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='borrowedbooks',
            old_name='bks_id',
            new_name='bks_iyd',
        ),
    ]
