# Generated by Django 4.0.6 on 2022-07-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0018_rename_itd_books_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbooks',
            old_name='bks_iyd',
            new_name='bks_id',
        ),
    ]
